#PBS -N negT_ls_0.1_-0.999_none_inf
#PBS -e /home/yud319/InexactPG/IPG/test/log/cache/negT_ls_0.1_-0.999_none_inf.err
#PBS -o /home/yud319/InexactPG/IPG/test/log/cache/negT_ls_0.1_-0.999_none_inf.out
#PBS -l nodes=1:ppn=4
#PBS -l mem=4gb,vmem=4gb
#PBS -q long
cd /home/yud319/InexactPG/IPG/test/negT
/home/yud319/anaconda3/bin/python runall.py --date 04_23_2021 --solver negT --loss ls --lam_shrink 0.1 --t -0.999 --safeguard_opt none --safeguard_const inf
