#PBS -N schimdt_ls_0.01_0.1
#PBS -e /home/yud319/InexactPG/IPG/test/log/cache/schimdt_ls_0.01_0.1.err
#PBS -o /home/yud319/InexactPG/IPG/test/log/cache/schimdt_ls_0.01_0.1.out
#PBS -l nodes=1:ppn=4
#PBS -l mem=4gb,vmem=4gb
#PBS -q long
cd /home/yud319/InexactPG/IPG/test/subgradient
/home/yud319/anaconda3/bin/python runall.py --date 04_18_2021 --solver schimdt --loss ls --lam_shrink 0.01 --schimdt_const 0.1
