#PBS -N naive_ls_0.01_schimdt_10
#PBS -e /home/yud319/InexactPG/IPG/test/log/cache/naive_ls_0.01_schimdt_10.err
#PBS -o /home/yud319/InexactPG/IPG/test/log/cache/naive_ls_0.01_schimdt_10.out
#PBS -l nodes=1:ppn=4
#PBS -l mem=8gb,vmem=8gb
#PBS -q long
cd /home/yud319/InexactPG/IPG/test/preDifferentInexact
/home/yud319/anaconda3/bin/python runall.py --date 04_10_2021 --solver naive --loss ls --lam_shrink 0.01 --safeguard_opt schimdt --safeguard_const 10
