#PBS -N naive_logit_0.1_1e-12_none_inf
#PBS -e /home/yud319/InexactPG/IPG/test/log/cache/naive_logit_0.1_1e-12_none_inf.err
#PBS -o /home/yud319/InexactPG/IPG/test/log/cache/naive_logit_0.1_1e-12_none_inf.out
#PBS -l nodes=1:ppn=4
#PBS -l mem=4gb,vmem=4gb
#PBS -q long
cd /home/yud319/InexactPG/IPG/test/subgradientProj
/home/yud319/anaconda3/bin/python runall.py --date 05_03_2021 --solver naive --loss logit --lam_shrink 0.1 --t 1e-12 --safeguard_opt none --safeguard_const inf
