#PBS -N 1_logit_0.1_10_0.1_projectedGD_True_1e-12_empty
#PBS -e /home/yud319/InexactPG/IPG/test/log/cache/1_logit_0.1_10_0.1_projectedGD_True_1e-12_empty.err
#PBS -o /home/yud319/InexactPG/IPG/test/log/cache/1_logit_0.1_10_0.1_projectedGD_True_1e-12_empty.out
#PBS -l nodes=1:ppn=4
#PBS -l mem=4gb,vmem=4gb
#PBS -q long
cd /home/yud319/InexactPG/IPG/test/natOG
/home/yud319/anaconda3/bin/python runall_patch.py --date 06_23_2021 --loss logit --lam_shrink 0.1 --group_size 10 --overlap_ratio 0.1 --tol 1e-05 --max_time 43200 --inexact_type 1 --subsolver projectedGD --warm_start True --largedb True --gamma1 1e-12
echo "1_logit_0.1_10_0.1_projectedGD_True_1e-12_empty.pbs" >> /home/yud319/InexactPG/IPG/test/pbs/natOG/finished.txt

