#PBS -N 2_logit_0.05_100_0.1_projectedGD_True_1e-12_0.1
#PBS -e /home/yud319/InexactPG/IPG/test/log/cache/2_logit_0.05_100_0.1_projectedGD_True_1e-12_0.1.err
#PBS -o /home/yud319/InexactPG/IPG/test/log/cache/2_logit_0.05_100_0.1_projectedGD_True_1e-12_0.1.out
#PBS -l nodes=1:ppn=4
#PBS -l mem=4gb,vmem=4gb
#PBS -q long
cd /home/yud319/InexactPG/IPG/test/natOG
/home/yud319/anaconda3/bin/python runall_patch.py --date 06_23_2021 --loss logit --lam_shrink 0.05 --group_size 100 --overlap_ratio 0.1 --tol 1e-05 --max_time 43200 --inexact_type 2 --subsolver projectedGD --warm_start True --gamma2 1e-12 --largedb True --nu 0.1
echo "2_logit_0.05_100_0.1_projectedGD_True_1e-12_0.1.pbs" >> /home/yud319/InexactPG/IPG/test/pbs/natOG/finished.txt

