#PBS -N 1_logit_0.1_100_0.3_projectedGD_True_1e-12_empty
#PBS -e /home/yud319/InexactPG/IPG/test/log/cache/1_logit_0.1_100_0.3_projectedGD_True_1e-12_empty.err
#PBS -o /home/yud319/InexactPG/IPG/test/log/cache/1_logit_0.1_100_0.3_projectedGD_True_1e-12_empty.out
#PBS -l nodes=1:ppn=4
#PBS -l mem=4gb,vmem=4gb
#PBS -q long
cd /home/yud319/InexactPG/IPG/test/latentOG
/home/yud319/anaconda3/bin/python runall.py --date 06_21_2021 --loss logit --lam_shrink 0.1 --group_size 100 --overlap_ratio 0.3 --inexact_type 1 --subsolver projectedGD --warm_start True --gamma1 1e-12
echo "1_logit_0.1_100_0.3_projectedGD_True_1e-12_empty.pbs" >> /home/yud319/InexactPG/IPG/test/pbs/latentOG/finished.txt

