#PBS -N 2_logit_0.05_10_0.3_projectedGD_True_1e-12_0.9
#PBS -e /home/yud319/InexactPG/IPG/test/log/cache/2_logit_0.05_10_0.3_projectedGD_True_1e-12_0.9.err
#PBS -o /home/yud319/InexactPG/IPG/test/log/cache/2_logit_0.05_10_0.3_projectedGD_True_1e-12_0.9.out
#PBS -l nodes=1:ppn=4
#PBS -l mem=4gb,vmem=4gb
#PBS -q long
cd /home/yud319/InexactPG/IPG/test/latentOG
/home/yud319/anaconda3/bin/python runall.py --date 06_21_2021 --loss logit --lam_shrink 0.05 --group_size 10 --overlap_ratio 0.3 --inexact_type 2 --subsolver projectedGD --warm_start True --gamma2 1e-12 --nu 0.9
echo "2_logit_0.05_10_0.3_projectedGD_True_1e-12_0.9.pbs" >> /home/yud319/InexactPG/IPG/test/pbs/latentOG/finished.txt

