#PBS -N 2_logit_0.8_100_0.3_projectedGD_True_1e-12_0.5
#PBS -e /home/yud319/InexactPG/IPG/test/log/cache/2_logit_0.8_100_0.3_projectedGD_True_1e-12_0.5.err
#PBS -o /home/yud319/InexactPG/IPG/test/log/cache/2_logit_0.8_100_0.3_projectedGD_True_1e-12_0.5.out
#PBS -l nodes=1:ppn=4
#PBS -l mem=4gb,vmem=4gb
#PBS -q long
cd /home/yud319/InexactPG/IPG/test/latentOG
/home/yud319/anaconda3/bin/python runall.py --date 06_12_2021 --loss logit --group_size 100 --overlap_ratio 0.3 --inexact_type 2 --subsolver projectedGD --warm_start True --gamma2 1e-12 --nu 0.5
echo "2_logit_0.8_100_0.3_projectedGD_True_1e-12_0.5.pbs" >> /home/yud319/InexactPG/IPG/test/pbs/latentOG/finished.txt

