#PBS -N 3_logit_0.1_10_0.1_projectedGD_True_3_1.0
#PBS -e /home/yud319/InexactPG/IPG/test/log/cache/3_logit_0.1_10_0.1_projectedGD_True_3_1.0.err
#PBS -o /home/yud319/InexactPG/IPG/test/log/cache/3_logit_0.1_10_0.1_projectedGD_True_3_1.0.out
#PBS -l nodes=1:ppn=4
#PBS -l mem=4gb,vmem=8gb
#PBS -q long
cd /home/yud319/InexactPG/IPG/test/latentOG
/home/yud319/anaconda3/bin/python runall_patch.py --date 07_02_2021 --loss logit --lam_shrink 0.1 --group_size 10 --overlap_ratio 0.1 --tol 1e-05 --max_time 43200 --inexact_type 3 --subsolver projectedGD --warm_start True --delta 3 --largedb True --schimdt_const 1.0
echo "3_logit_0.1_10_0.1_projectedGD_True_3_1.0.pbs" >> /home/yud319/InexactPG/IPG/test/pbs/latentOG/finished.txt

