#PBS -N naive_logit_0.1_laststep_1
#PBS -e /home/yud319/InexactPG/IPG/test/log/cache/naive_logit_0.1_laststep_1.err
#PBS -o /home/yud319/InexactPG/IPG/test/log/cache/naive_logit_0.1_laststep_1.out
#PBS -l nodes=1:ppn=4
#PBS -l mem=8gb,vmem=8gb
#PBS -q long
cd /home/yud319/InexactPG/IPG/test/preDifferentInexact
/home/yud319/anaconda3/bin/python runall.py --date 04_10_2021 --solver naive --loss logit --lam_shrink 0.1 --safeguard_opt laststep --safeguard_const 1
